version: '3.9'

services:
  server:
    container_name: truephone_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/server/Dockerfile
    command: yarn start:dev
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - db
    networks:
      - app

  client:
    container_name: truephone_client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/client/Dockerfile
    command: yarn dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app

  db:
    container_name: truephone_db
    image: postgres
    restart: unless-stopped
    volumes:
      - './.data/db:/var/lib/postgresql/data'
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGUSER=${DB_USERNAME}
      - PGPASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_DATABASE}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app

networks:
  app:
    driver: bridge
